### ISSUE TITLE
diet data differences

### ISSUE THREAD

**Issue by MaC-Perez** [thefaylab/hydra_diag#21]
Hi @gavinfay  I still have the problem with the diet data. I couldn't fix the difference between the observed diet data (hydraDataList$observedSurvDiet = length 56652) and the predicted values (pred_diet = length 56412). I understand how the difference is produced, what does not fit me is the number 56652-56412= 240. Could you please check the code (*line 245 in hydra-diagnostics.RMD file) and give me some clue of what I'm not seeing.

**Comment by gavinfay** [comment]
@MaC-Perez Can you send me the call to `hydraplots()` you are using so I can try to replicate this?

**Comment by MaC-Perez** [comment]
I am working directly on the project hydra_diag.Rproj and the hydraplots.R is in the folder "R"




MSc. María Cristina Pérez Cuesta
 Departamento Evaluación de Recursos
        Instituto de Fomento Pesquero
        Blanco 839, Valparaíso, Chile.
             Fono: (032) 22151503

________________________________
De: Gavin Fay ***@***.***>
Enviado: miércoles, 5 de octubre de 2022 8:16
Para: thefaylab/hydra_diag ***@***.***>
Cc: Maria Cristina Perez ***@***.***>; Mention ***@***.***>
Asunto: Re: [thefaylab/hydra_diag] diet data differences (Issue #21)


@MaC-Perez<https://github.com/MaC-Perez> Can you send me the call to hydraplots() you are using so I can try to replicate this?

**Comment by gavinfay** [comment]
Yep. But what arguments are you passing to the hydraplots() function?
Which combination of data object and report files are generating the error?

For example, for some of the GB runs I am running:

```
hydraplots(data = "../../hydra_sim/GB-input/GB-5bin-hydraDataList_msk.rds",
           report = "../../hydra_sim/hydra_sim.rep",
           outfile = "../outputs/junk_msk.html",
           plot_comps = TRUE)
```

**Comment by MaC-Perez** [comment]
@gavinfay 
I sent them to your email

**Comment by gavinfay** [comment]
Looks like you don't have predictions for the observations that are zeroes Suggest updating to most recent version of `hydra_sim`.
Quick fix to resolve the lengths of the vectors in the current files would be to do a filter for these rows on the `obs_diet` object.
e.g. 
`%>% filter(value != 0)`
Generally suggest doing these hardwires before passing the data_object to hydraplots rather than during the diagnostics.Rmd so that desired behavior is preserved across files, but I think in this case such an add won't cause brittleness.

**Comment by gavinfay** [comment]
More robust solution. Trap added in [9e68128](https://github.com/thefaylab/hydra_diag/commit/9e68128421ee949515ba548e648fc3bf70042c4a) to remove the zero rows from the data object only when there is a mismatch between object lengths, as this should cover the older cases and also not endanger ones where zeroes are predicted.
