### ISSUE TITLE
Create diagnostic plots for size/diet composition fits for Hydra

### ISSUE THREAD

**Issue by gavinfay** [thefaylab/hydra_diag#4]
Adapt existing r4ss code to generate set of diagnostic plots for the fits to the composition data (both size composition & diet composition).
Adapt SSplotComps() function:
https://github.com/r4ss/r4ss/blob/main/R/SSplotComps.R

    ### { # loop over species
    ###
    ### subplot 1: multi-panel composition plot. (survey and fishery size comps)
    ### subplot 2: single panel bubble plot for numbers at length (survey and fishery size comps)
    ### subplot 3: multi-panel bubble plots for conditional age-at-length. (diet, prey wt given predator size class)
    ### subplot 4: multi-panel plot of fit to conditional age-at-length for specific years (diet, prey wt given predator size class)
    ### subplot 5: Pearson residuals for A-L key. (diet, prey wt given predator size class)
    ### subplot 6: multi-panel plot of point and line fit to conditional
    ###            age-at-length for specific length bins (diet, prey wt given predator size class)
    ### subplot 7: sample size plot (all types of data)
    ### subplot 8: TA1.8 Francis weighting plot (fishery and survey size comps)
    ###
    ### } # end loop over species
    ###
    ### subplot 21: by fleet aggregating across years

**Comment by gavinfay** [comment]
For the aggregated plots, I would do the same thing that they do with SS, and weight the numbers in each bin by sample size. Thus, multiply the annual observed and predicted proportions by the sample size, sum numbers over years, and then divide by the total across years to get the aggregated proportions.
(e.g. see lines 509-520 of the SSplotComps() function)

**Comment by MaC-Perez** [comment]
Hi @gavinfay just to check ... for the diet comp plots I selected one predator and one prey species for each plot. So, I have a multiplot with boxes from year 1 to year 80 for predator 1 and prey 1 (for example). 

something like this....

<img width="538" alt="diet_1" src="https://user-images.githubusercontent.com/62034424/174451692-9af22b0f-360f-4d5a-b899-65e4efa71d7d.png">

**Comment by gavinfay** [comment]
@MaC-Perez The Diet composition data are proportions of stomach weights for each prey, given a predator size class. So, you want the annual compositions to be over prey species, not length bins of predators as here.
The simple approach would be to have separate sets of panels for each size class of each predator. This will be lots of plots but at least will show the fits. I suspect some alternative that is able to put multiple comps on the same panel will be useful, perhaps something like stacked bar charts of the proportions with bars in a panel corresponding to each predator size class, like the MS-KEYRUNS plots, and visual comparisons between data and model predictions like those Kiersten showed.

**Comment by MaC-Perez** [comment]
Yes, you're right @gavinfay  .... I do not know what I was doing. I am visualizing the plots in excel first to better understand how to take the data... I have this kind of plot for predicted and observed values but it is very difficult to visualize the information

![image](https://user-images.githubusercontent.com/62034424/175848910-c0ad01ad-a74f-408f-8df9-ccb6015647f1.png)

**Comment by MaC-Perez** [comment]
Hi @gavinfay ! 

I already did the cycle for all the figures, but when I try to do the plots with the estimated and predicted values in the same variable (type), I get stuck an error when adding this line...

geom_text(data=temp_size, aes(x = 4.8, y = 0.5, label = mu_ss), size=3) +

Error in FUN(X[[i]], ...) : object 'type' not found.  Could you please tell me what am I missing?

I already uploaded the updated code, start in line 96
