### ISSUE TITLE
rep file changes

### ISSUE THREAD

**Issue by sgaichas** [thefaylab/hydra_diag#5]
@gavinfay and @MaC-Perez I'm trying to use the diagnostics code with the report file from the current [hydra_sim.tpl](https://github.com/thefaylab/hydra_sim/blob/main/hydra_sim.tpl) but am finding that the  `hydra_sim.rep` produced when I run the code is structured differently from the `hydra_sim.rep` in this repository, so that the function `reptoRlist` in `read.report` is not reading in the same information. 

The issue is starting lines in the rep file with the same word and having multiple text lines describing the dataset breaks `reptoRlist`.

Is the version of `hydra_sim.rep` in this repository the correct one, so the report section in the .tpl in hydra_sim repo is  outdated? Or is the .tpl the most recent and do we need to change the report section of .tpl to single line names to allow `reptoRlist` to work?

I've started my own branch of hydra_sim to play with different configurations, but I don't want to make changes that I may have missed elsewhere.

Thanks!

**Comment by gavinfay** [comment]
I will take a look. I believe @MaC-Perez has been working independently in the diag repo so not sure how recent the .rep file was. It's very possible these have diverged but shouldn't be too much. Can look into this 8/12.

**Comment by gavinfay** [comment]
`.rep` object names now match those expected by `R/diagnostics.R`.

Cleaned up the repository quite extensively. 
The `diagnostics` script works on the test data/rep files in this repo but it likely won't on others as configuration is largely hard coded. (object dimensions, number of bins, etc.). Lots of new issues coming!
